# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
include: "rules/common.smk"

rule all:
    input:
        "data/processed/qc/multiqc.html",
        #expand("data/interim/trimmed/{sample}-{unit}.1.fastq.gz", sample=SAMPLES, unit=UNITS),
        #expand("data/interim/trimmed/{sample}-{unit}.2.fastq.gz", sample=SAMPLES, unit=UNITS),
        expand("data/processed/trinity/trinity_{sample}-{unit}.Trinity.fasta", sample=SAMPLES, unit=UNITS),

include: "rules/qc.smk"
include: "rules/trinity.smk"
